### ISSUE TITLE
Feature request: Add ability to use parent trace

### ISSUE THREAD

**Issue by emanuelef** [tekul/rust-tracing-otlp#1]
Hi, this code has been really helpful to me. I was wondering if you can add the ability to attach spans to the current trace parent. This in case the service is called from another service that has created a trace.
Thanks

**Comment by tekul** [comment]
Hi. I'm glad you found it useful! I believe `tracing-actix-web` should automatically [take care of propagating the trace ID](https://github.com/LukeMathWalker/tracing-actix-web/blob/e097e5644b338d77cf6f22aed6db50941098fc09/src/otel.rs#L67) if you set the appropriate OpenTelemetry flag for the crate (i.e. `opentelemetry_0_22` in this case). It's not something I've tested, but when I find time I'll try and add a bit about it to the article. It should just require adding a `traceparent` header to the incoming request. The header value would contain the ID for the span.

**Comment by emanuelef** [comment]
Thanks, yes I'm aware of what is needed to propagate the trace across different services.
I did that for different languages and I'm now trying for Rust, I was hoping there was some middleware for adding that was just requiring few lines of code.

**Comment by tekul** [comment]
I'm not sure what you mean. I think the existing code in this code should do it automatically as long as you change the `Cargo.toml` file to add that flag to `tracing-actix-web` (which is the middleware we are using here). It shouldn't need any code changes.

Edit: I updated the dependencies and added the feature flag. It shouldn't break any of the existing code anyway.

**Comment by emanuelef** [comment]
Thanks, I'll try that.

**Comment by tekul** [comment]
Let me know what you find. I haven't really looked into using tracing with multiple processes so I don't really have a good idea of how it fits together in practice.

**Comment by emanuelef** [comment]
I'm closing this as it was created for a request and not to report an issue. Would be interesting to have a Discussion section that is available in GitHub.
